# Generated by Django 3.2.12 on 2025-04-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookedequipments', '0005_auto_20240614_0914'),
        ('bookedequipments', '0005_auto_20240614_0925'),
    ]

    operations = [
    ]
