# Generated by Django 3.2.12 on 2025-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedequipments', '0006_merge_0005_auto_20240614_0914_0005_auto_20240614_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedequipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
