# Generated by Django 3.2.12 on 2025-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_remove_equipmentcategory_nbrequipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='nbrEquipments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='image',
            field=models.ImageField(default='/default_equipment_image/default.jpg', upload_to='default_equipment_image'),
        ),
    ]
